name: CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew

      - run: ./gradlew test
      - run: ./gradlew build

  compatibility-test:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idea-version: ['2024.2', '2025.1']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - run: ./gradlew test
        env:
          IDEA_VERSION: ${{ matrix.idea-version }}

  publish:
    needs: [ build-test, compatibility-test ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew

      - name: Publish Plugin
        run: ./gradlew publishPlugin
        env:
          JETBRAINS_PUBLISH_TOKEN: ${{ secrets.JETBRAINS_PUBLISH_TOKEN }}
          CHANNEL: ${{
            contains(github.ref_name, 'alpha') && 'alpha' ||
            (contains(github.ref_name, 'beta') && 'beta' || 'default')
            }}