name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew

      - run: ./gradlew test
      - run: ./gradlew build

  compatibility-test:
    needs: build-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idea-version: ['2024.2', '2025.1']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - run: ./gradlew test
        env:
          IDEA_VERSION: ${{ matrix.idea-version }}
